// Core session management

// Config paths
export { APP_NAME, CONFIG_DIR_NAME, ENV_PREFIX, FILE_PREFIX, getAgentDir, VERSION } from "./config.js";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.js";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.js";
export {
	type CavecrewBuilderResult,
	type CavecrewInvestigationResult,
	type CavecrewPlan,
	type CavecrewProviderFixtures,
	type CavecrewRequest,
	type CavecrewResult,
	type CavecrewReviewResult,
	type CavecrewTerminalState,
	runCavecrew,
} from "./core/cavecrew-runtime.js";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.js";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.js";
// Execution diagnostics (doctor lsp|tools|scheduler|jobs)
export {
	collectExecutionDiagnostics,
	type ExecutionDiagnostics,
	type ExecutionDiagnosticsInput,
	formatExecutionDiagnostics,
} from "./core/execution-diagnostics.js";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppAction,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionForkEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionSwitchEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandLocation,
	SlashCommandSource,
	TerminalInputHandler,
	ToolCallEvent,
	ToolDefinition,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WriteToolCallEvent,
} from "./core/extensions/index.js";
export {
	createExtensionRuntime,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
	wrapToolsWithExtensions,
	wrapToolWithExtensions,
} from "./core/extensions/index.js";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.js";
// Durable background-job registry (1.4.0)
export { type BackgroundJobRecord, BackgroundJobRegistry, createJobTools } from "./core/jobs/index.js";
// Native Language Server Protocol subsystem (1.4.0)
export {
	createLspTools,
	DEFAULT_LANGUAGE_SERVERS,
	JsonRpcClient,
	LspClient,
	LspRuntime,
	type LspServerIdentity,
	LspServerManager,
} from "./core/lsp/index.js";
export {
	canonicalizeMcp,
	classifyMcpToolEffects,
	createMcpCapabilitySnapshot,
	createMcpIdentity,
	detectCapabilityDrift,
	type McpCapabilitySnapshot,
	type McpEffectClass,
	type McpHealth,
	type McpServerConfig,
	type McpServerIdentity,
	type McpToolEffects,
	type McpToolSchema,
	type McpTransport,
	type McpValidationIssue,
	type McpValidationResult,
	mcpSha256,
	redactMcpDiagnostics,
	validateMcpConfig,
	validateMcpResourceUri,
	validateMcpToolSchemas,
} from "./core/mcp.js";
export {
	createMcpClient,
	type McpCallResult,
	McpClient,
	type McpClientOptions,
	type McpConnectionState,
	type McpHealthEvent,
	type McpJsonRpcError,
	type McpJsonRpcResponse,
	McpTransportError,
	redactMcpError,
} from "./core/mcp-client.js";
export {
	buildStructuredMemoryCompareData,
	buildStructuredMemoryHistoryData,
	type MemorySnapshotContractContext,
	type StructuredMemoryCompareData,
	type StructuredMemoryCompareEmptyHistoryData,
	type StructuredMemoryCompareInitialSnapshotData,
	type StructuredMemoryCompareOkData,
	type StructuredMemoryCompareSelectorResolutionFailedData,
	type StructuredMemoryHistoryData,
	type StructuredMemorySnapshot,
	type StructuredResolvedSnapshotSelector,
	type StructuredSnapshotSelectorCandidate,
	type StructuredSnapshotSelectorIssue,
} from "./core/memory-snapshot-contract.js";
export { convertToLlm } from "./core/messages.js";
export { ModelRegistry } from "./core/model-registry.js";
export {
	collectDiagnostics,
	createSupportBundle,
	type DiagnosticCheckResult,
	type DiagnosticReport,
	diffRuns,
	type EventPage,
	type EventQuery,
	type EventReadIssue,
	type EventReadResult,
	envelopeForEntry,
	type JensenEventEnvelope,
	listEvidence,
	loadProjectionFromSession,
	OBSERVABILITY_SCHEMA_VERSION,
	projectionReplay,
	projectRun,
	queryEvents,
	type RunDiff,
	type RunDiffField,
	type RunProjection,
	readSessionEvents,
	renderReplay,
	type SupportBundleManifest,
	sanitize,
	supportBundlePreview,
} from "./core/operability.js";
export {
	inspectSupportBundle,
	type ReexecutionOptions,
	type ReexecutionResult,
	rebuildStorageIndex,
	reexecuteRun,
	type SimulationReplay,
	type StorageIndex,
	type StoragePruneEntry,
	type StoragePruneResult,
	simulateReplay,
	storagePrune,
} from "./core/operability-runtime.js";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.js";
export { DefaultPackageManager } from "./core/package-manager.js";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.js";
export { DefaultResourceLoader } from "./core/resource-loader.js";
export { defaultWorkspaceStateDir, handleWorkspaceCommand } from "./core/safety/cli.js";
export type {
	ExecutionMode,
	LeaseRecord,
	LeaseResult,
	MutationLifecycleEvent,
	MutationOutcome,
	PolicyDecision,
	PolicyEvaluation,
	RecoveryClass,
	RollbackConflict,
	RollbackResult,
	TransactionRecord,
	WorkspaceCheckpoint,
	WorkspaceEdit,
	WorkspaceSafetyOptions,
} from "./core/safety/index.js";
// Safe autonomous execution
export {
	CheckpointError,
	CheckpointStore,
	isSecretPath,
	PolicyApprovalRequiredError,
	PolicyDeniedError,
	PolicyEngine,
	PRODUCTION_TOOL_EFFECTS,
	sha256,
	TransactionError,
	validateToolEffects,
	WorkspaceBoundary,
	WorkspaceBoundaryError,
	WorkspaceLeaseError,
	WorkspaceLeaseStore,
	WorkspaceSafety,
	WorkspaceTransactionManager,
} from "./core/safety/index.js";
// SDK for programmatic usage
export {
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	// Factory
	createAgentSession,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createPowerShellTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type PromptTemplate,
	// Pre-built tools (use process.cwd())
	readOnlyTools,
} from "./core/sdk.js";
export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.js";
export {
	type CompactionSettings,
	type ImageSettings,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
} from "./core/settings-manager.js";
export {
	applySkillMigration,
	packagedCavecrewPath,
	previewSkillMigration,
	type SkillMigrationPreview,
	skillMigrationSourceExists,
} from "./core/skill-migration.js";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.js";
// Tool storm breaker (1.4.0)
export {
	fingerprintCall,
	StormBreaker,
	TOOL_CALL_DUPLICATE_NO_PROGRESS,
	TOOL_CALL_STORM_BLOCKED,
	TOOL_STRATEGY_PIVOT_REQUIRED,
} from "./core/storm/index.js";
export { handleSubagentCommand } from "./core/subagent-cli.js";
// Canonical subagent registry and policy contracts
export {
	ANALYTICAL_MODEL,
	ANALYTICAL_PROVIDER,
	assertCanonicalProductionAgents,
	BUILTIN_SUBAGENT_DEFINITIONS,
	getCanonicalSubagentRegistry,
	type ModelResolutionPolicy,
	type RegistryDiagnostic,
	type ResolvedSubagent,
	resolveSubagentModel,
	type SkillDependencyDiagnostic,
	SUBAGENT_POLICY_EFFECTS,
	type SubagentBudget,
	type SubagentDefinition,
	type SubagentExecutionMode,
	type SubagentModelResolution,
	SubagentRegistry,
	type SubagentResolutionError,
	type SubagentResolutionErrorCode,
	type SubagentRetrievalPolicy,
	type SubagentRole,
	subagentRetrievalPolicy,
	validateSkillAgentReferences,
	validateSubagentOutput,
} from "./core/subagent-registry.js";
export {
	createSubagentContextPacket,
	getResolvedModelForDispatch,
	type ParentSubagentPolicy,
	type ResolvedSubagentInvocation,
	resolveSubagentInvocation,
	type SubagentContextPacket,
	SubagentRuntimeError,
	type SubagentRuntimeErrorCode,
	validateParentSubagentOutput,
} from "./core/subagent-runtime.js";
// Tool-call normalization & conservative repair (1.4.0)
export {
	canonicalStableStringify,
	type NormalizedToolCall,
	normalizeToolCall,
	runToolCallPipeline,
	scavengeToolCall,
	ToolCallNormalizationError,
	type ToolCallRepair,
	validateAgainstSchema,
} from "./core/tool-call/index.js";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	bashTool,
	type CreateLocalPowerShellOperationsOptions,
	codingTools,
	createLocalPowerShellOperations,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	editTool,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	findTool,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	grepTool,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	lsTool,
	type PowerShellOperations,
	type PowerShellToolDetails,
	type PowerShellToolInput,
	type PowerShellToolOptions,
	powershellTool,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	readTool,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	writeTool,
} from "./core/tools/index.js";
// Working context surface
export {
	buildWorkingContext,
	buildWorkingContextDelegatedWorkSummary,
	buildWorkingContextMemorySummary,
	buildWorkingContextTodoSummary,
	type WorkingContext,
	type WorkingContextDelegatedWorkSummary,
	type WorkingContextMemorySummary,
	type WorkingContextTodoSummary,
} from "./core/working-context.js";
export { defaultIndexConfig, resolveIndexConfig, type WorkspaceIndexConfig } from "./core/workspace/config.js";
export {
	buildRetrievalContextPacket,
	type RetrievalEvidenceRecord,
	renderPacketAsEvidence,
	toEvidenceRecord,
} from "./core/workspace/context-packet.js";
export {
	DisabledEmbeddingBackend,
	type EmbeddingConfig,
	type EmbeddingMode,
	FixtureEmbeddingBackend,
	LocalEmbeddingBackend,
	resolveEmbeddingBackend,
} from "./core/workspace/embedding.js";
export {
	sanitizeEventPayload,
	WORKSPACE_INDEX_EVENTS,
	type WorkspaceIndexDurableEvent,
	type WorkspaceIndexEventName,
} from "./core/workspace/events.js";
export { resolveWorkspaceIdentity, workspaceIndexDir } from "./core/workspace/identity.js";
// Workspace intelligence (1.7.0): durable, hybrid lexical/symbolic/semantic retrieval
export {
	type IndexStatus,
	type SearchOptions,
	WorkspaceIndex,
	workspaceDoctorChecks,
} from "./core/workspace/index.js";
export { type PlannerInput, planQuery } from "./core/workspace/planner.js";
export { executeRetrieval, type RetrieveOptions, revalidateResult } from "./core/workspace/retrieve.js";
export type {
	EmbeddingBackend,
	HybridCandidateScore,
	IndexedChunk,
	IndexedFileRecord,
	IndexedSymbol,
	RetrievalContextPacket,
	RetrievalPlan,
	SymbolRelation,
	WorkspaceIdentity,
	WorkspaceIndexGeneration,
	WorkspaceRetrievalResult,
} from "./core/workspace/types.js";
// Main entry point
export { main } from "./main.js";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type PrintModeOptions,
	runPrintMode,
	runRpcMode,
} from "./modes/index.js";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	appKey,
	appKeyHint,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	editorKey,
	FooterComponent,
	keyHint,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.js";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.js";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.js";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.js";
// Shell utilities
export { getShellConfig } from "./utils/shell.js";
