/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.js";
export { type BashExecutorOptions, type BashResult, executeBash, executeBashWithOperations } from "./bash-executor.js";
export type { CompactionResult } from "./compaction/index.js";
export {
	applyDelegatedResult,
	buildDelegatedWorkSummary,
	type DelegatedMode,
	type DelegatedStatus,
	type DelegatedTask,
	type DelegatedWorkSummary,
	extractDelegatedTask,
	getRecentDelegatedTasks,
	mergeDelegatedTask,
	syncDelegatedWork,
} from "./delegated-work.js";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.js";
// Extensions system
export {
	type AgentEndEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type ContextEvent,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionForkEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionSwitchEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
} from "./extensions/index.js";
export {
	buildStructuredMemoryCompareData,
	buildStructuredMemoryHistoryData,
	type MemorySnapshotContractContext,
	type StructuredMemoryCompareData,
	type StructuredMemoryCompareEmptyHistoryData,
	type StructuredMemoryCompareInitialSnapshotData,
	type StructuredMemoryCompareOkData,
	type StructuredMemoryCompareSelectorResolutionFailedData,
	type StructuredMemoryHistoryData,
	type StructuredMemorySnapshot,
	type StructuredResolvedSnapshotSelector,
	type StructuredSnapshotSelectorCandidate,
	type StructuredSnapshotSelectorIssue,
} from "./memory-snapshot-contract.js";
export {
	buildWorkingContext,
	buildWorkingContextDelegatedWorkSummary,
	buildWorkingContextMemorySummary,
	buildWorkingContextTodoSummary,
	type WorkingContext,
	type WorkingContextDelegatedWorkSummary,
	type WorkingContextMemorySummary,
	type WorkingContextTodoSummary,
} from "./working-context.js";
